server:
  port: 8090

databricks:
  host: ${DATABRICKS_HOST:}
  token: ${DATABRICKS_TOKEN:}
  warehouseId: ${DATABRICKS_WAREHOUSEID:}
  httpPath: ${DATABRICKS_HTTPPATH:/sql/1.0/warehouses/${DATABRICKS_WAREHOUSEID:}}
  connectTimeoutMs: ${DATABRICKS_TIMEOUT_MS:3000}
  readTimeoutMs: ${DATABRICKS_READTIMEOUT_MS:30000}

cache:
  pageSize: ${CACHE_PAGE_SIZE:500}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ssl: ${REDIS_SSL:false}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    timeoutMs: ${REDIS_TIMEOUT_MS:3000}
    chunkTtlSeconds: ${REDIS_CHUNK_TTL:600}
    cacheFirstChunkMaxWaitMs: ${CACHE_FIRST_CHUNK_MAX_WAIT_MS:15000}
    cacheFirstChunkPollMs: ${CACHE_FIRST_CHUNK_POLL_MS:100}

logging:
  level:
    com.mm.customreportbuilder.databricks: DEBUG

app:
  facts:
    fact_product:
      path: classpath:sql/facts/fact_product.sql
  dims:
    categories:
      path: classpath:sql/dims/categories.sql
      ttlSeconds: 900
    brands:
      path: classpath:sql/dims/brands.sql
      ttlSeconds: 900